// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rmvnorm
NumericMatrix rmvnorm(int nsamples, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP _bettertogether_rmvnorm(SEXP nsamplesSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm(nsamples, mean, covariance));
    return rcpp_result_gen;
END_RCPP
}
// dmvnorm
NumericVector dmvnorm(const NumericMatrix& x, const NumericVector& mean, const NumericMatrix& covariance);
RcppExport SEXP _bettertogether_dmvnorm(SEXP xSEXP, SEXP meanSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(dmvnorm(x, mean, covariance));
    return rcpp_result_gen;
END_RCPP
}
// systematic_resampling_
IntegerVector systematic_resampling_(const NumericVector& weights);
RcppExport SEXP _bettertogether_systematic_resampling_(SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(systematic_resampling_(weights));
    return rcpp_result_gen;
END_RCPP
}
// systematic_resampling_n_
IntegerVector systematic_resampling_n_(const NumericVector& weights, int ndraws);
RcppExport SEXP _bettertogether_systematic_resampling_n_(SEXP weightsSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    rcpp_result_gen = Rcpp::wrap(systematic_resampling_n_(weights, ndraws));
    return rcpp_result_gen;
END_RCPP
}
// systematic_resampling_n_u_
IntegerVector systematic_resampling_n_u_(const NumericVector& weights, int ndraws, double u);
RcppExport SEXP _bettertogether_systematic_resampling_n_u_(SEXP weightsSEXP, SEXP ndrawsSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(systematic_resampling_n_u_(weights, ndraws, u));
    return rcpp_result_gen;
END_RCPP
}
// wmean_
NumericVector wmean_(const NumericMatrix& x, const NumericVector& unnormalized_w);
RcppExport SEXP _bettertogether_wmean_(SEXP xSEXP, SEXP unnormalized_wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unnormalized_w(unnormalized_wSEXP);
    rcpp_result_gen = Rcpp::wrap(wmean_(x, unnormalized_w));
    return rcpp_result_gen;
END_RCPP
}
// wcovariance_
NumericMatrix wcovariance_(const NumericMatrix& x, const NumericVector& unnormalized_w, const NumericVector& xbar);
RcppExport SEXP _bettertogether_wcovariance_(SEXP xSEXP, SEXP unnormalized_wSEXP, SEXP xbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type unnormalized_w(unnormalized_wSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type xbar(xbarSEXP);
    rcpp_result_gen = Rcpp::wrap(wcovariance_(x, unnormalized_w, xbar));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_module_mvnorm();
RcppExport SEXP _rcpp_module_boot_module_waverage();

static const R_CallMethodDef CallEntries[] = {
    {"_bettertogether_rmvnorm", (DL_FUNC) &_bettertogether_rmvnorm, 3},
    {"_bettertogether_dmvnorm", (DL_FUNC) &_bettertogether_dmvnorm, 3},
    {"_bettertogether_systematic_resampling_", (DL_FUNC) &_bettertogether_systematic_resampling_, 1},
    {"_bettertogether_systematic_resampling_n_", (DL_FUNC) &_bettertogether_systematic_resampling_n_, 2},
    {"_bettertogether_systematic_resampling_n_u_", (DL_FUNC) &_bettertogether_systematic_resampling_n_u_, 3},
    {"_bettertogether_wmean_", (DL_FUNC) &_bettertogether_wmean_, 2},
    {"_bettertogether_wcovariance_", (DL_FUNC) &_bettertogether_wcovariance_, 3},
    {"_rcpp_module_boot_module_mvnorm", (DL_FUNC) &_rcpp_module_boot_module_mvnorm, 0},
    {"_rcpp_module_boot_module_waverage", (DL_FUNC) &_rcpp_module_boot_module_waverage, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bettertogether(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
